### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by ehsan-shv** [lmiller1990/v-switch#2]
my component:
```
<template>
  <v-switch :case="number">
    <template v-for="num in numbers" v-slot:[num]> Number: {{ num }} </template>

    <template #default> Default </template>
  </v-switch>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import VSwitch from '@lmiller1990/v-switch'

export default defineComponent({
  components: {
    VSwitch,
  },

  setup() {
    const number = ref(1)
    const numbers = [1, 2, 3, 4, 5]

    return {
      number,
      numbers,
    }
  },
})
</script>
```

and package.json:

```
{
  "name": "v3",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@lmiller1990/v-switch": "^1.0.0",
    "core-js": "^3.6.5",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended",
      "@vue/prettier"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```
but I got this error:
![image](https://user-images.githubusercontent.com/33913956/126045623-b5f7249f-ea9c-4f6f-a988-e35e3c570302.png)

**Comment by lmiller1990** [comment]
Weird, for some reason it is reading the `browser` build.

I fixed this by doing `import VSwitch from '@lmiller1990/v-switch/dist/v-switch.cjs.js'` temporarily, but we should find out why this is happening. Maybe `browser` is not even needed in `package.json`.

**Comment by lmiller1990** [comment]
Fixed in 1.0.1. https://github.com/lmiller1990/v-switch/commit/6311807ac926f62b6127b3057cb5ea8911a24745
Try updating to the latest version - it should work correctly now with Vue CLI projects.

**Comment by ehsan-shv** [comment]
tnx, updated to 1.0.1 version and got this error:
![image](https://user-images.githubusercontent.com/33913956/126457846-2f80d17f-5f52-490b-a290-28185219a3b8.png)
I don't know, maybe I went wrong. :/

**Comment by lmiller1990** [comment]
I reproduced the problem. Fixed: https://github.com/lmiller1990/v-switch/commit/bf5976fa0016662ea6a453453606e62b1a8fdb48

I was missing the `"types"` key. Please try `1.1.0`, which I just released - `npm install @lmiller1990/v-switch@latest` should do it.

**Comment by lmiller1990** [comment]
@ehsan-shv let me know if this isn't working after you install 1.1.0. Thanks!

**Comment by ehsan-shv** [comment]
Yes, it worked. another issue is that it is not compatible with Nuxt. do you have a plan for packaging Vue components that going to be compatible with both Vue and Nuxt(SSR)? if you want I can create another issue and explain there.

**Comment by lmiller1990** [comment]
I have not tried with Nuxt and Vue 3 yet - is Nuxt working with Vue 3?

Seems like we should support Nuxt. If you found a bug with SSR, please make a new issue like you suggested 👍

**Comment by ehsan-shv** [comment]
At this time Nuxt does not support Vue3. so we should wait. :)
