### ISSUE TITLE
Not working missing dist directory

### ISSUE THREAD

**Issue by zizu-kun** [lmiller1990/v-switch#4]
the version 1.3.0 when installed via npm (I don't know about yarn) the dist directory is not visible in node_modules.
only 1.1.0 works fine since it has the dist directory.

**Comment by SIGSTACKFAULT** [comment]
same here

**Comment by lmiller1990** [comment]
Sorry, just saw this. That's strange. Let me fix it.

**Comment by lmiller1990** [comment]
Seems fine with 1.4.0.
